alter table CARSERVICE_REPAIR add constraint FK_CARSERVICE_REPAIR_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references CARSERVICE_EMPLOYEE(ID);
create index IDX_CARSERVICE_REPAIR_ON_EMPLOYEE on CARSERVICE_REPAIR (EMPLOYEE_ID);
