alter table CARSERVICE_CAR_SERVICE add constraint FK_CARSERVICE_CAR_SERVICE_ON_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID);
create index IDX_CARSERVICE_CAR_SERVICE_ON_CREATOR on CARSERVICE_CAR_SERVICE (CREATOR_ID);
