-- begin CARSERVICE_CAR_SERVICE
alter table CARSERVICE_CAR_SERVICE add constraint FK_CARSERVICE_CAR_SERVICE_ON_CITY foreign key (CITY_ID) references CARSERVICE_CITY(ID)^
create index IDX_CARSERVICE_CAR_SERVICE_ON_CITY on CARSERVICE_CAR_SERVICE (CITY_ID)^
-- end CARSERVICE_CAR_SERVICE
-- begin CARSERVICE_EMPLOYEE
alter table CARSERVICE_EMPLOYEE add constraint FK_CARSERVICE_EMPLOYEE_ON_CAR_SERVICE foreign key (CAR_SERVICE_ID) references CARSERVICE_CAR_SERVICE(ID)^
create index IDX_CARSERVICE_EMPLOYEE_ON_CAR_SERVICE on CARSERVICE_EMPLOYEE (CAR_SERVICE_ID)^
-- end CARSERVICE_EMPLOYEE
